### ISSUE TITLE
Two typos

### ISSUE THREAD

**Issue by brirush84** [moonymeric/Saving_Elensefar#2]
In scenario 1:
"He also brought many of the archer from his elvish house out of the northlands, to sail with him on his ship."

archer -> archers

In r0 high seas:
"we must either land on an island or capture an enemy ship ever 6 weeks."

ever->every

Loved playing this, thanks for maintaining this branch!

**Comment by moonymeric** [comment]
If you find more typos, simply keep listing them in this issue. Because changing any string would break all 14 translations, I will not address each typo immediately. Instead, my plan is to collect them and fix all in one big operation. Thanks for your help!

**Comment by moonymeric** [comment]
Fixed in 15e1b99
